FROM mcr.microsoft.com/dotnet/sdk:10.0

# Prereqs
RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    gnupg \
    curl \
    docker.io \
 && rm -rf /var/lib/apt/lists/*

# Add Google Cloud SDK repo
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
    | tee /etc/apt/sources.list.d/google-cloud-sdk.list \
 && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
    | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg

# Install gcloud
RUN apt-get update && apt-get install -y --no-install-recommends \
    google-cloud-cli \
 && rm -rf /var/lib/apt/lists/*
