// <auto-generated />
using Cicd.Web.Admin.Services.Builds;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cicd.Web.Admin.Services.Builds.Migrations
{
    [DbContext(typeof(BuildSyncDbContext))]
    partial class BuildSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Cicd.Web.Admin.Services.Builds.BuildRunRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArtifactsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BuildInfoJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Building")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CausesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("SyncedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobName", "Building");

                    b.HasIndex("JobName", "Number")
                        .IsUnique();

                    b.ToTable("BuildRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
