// <auto-generated />
using System;
using Jenkins.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jenkins.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JenkinsCiDbContext))]
    [Migration("20260701013426_AddBuildKindAndAppHostPath")]
    partial class AddBuildKindAndAppHostPath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jenkins.Domain.Builds.ArtifactPublication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Registry")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("_tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tags");

                    b.HasKey("Id");

                    b.HasIndex("BuildArtifactId");

                    b.ToTable("ArtifactPublication", (string)null);
                });

            modelBuilder.Entity("Jenkins.Domain.Builds.Build", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CiBuildNumber")
                        .HasColumnType("int");

                    b.Property<string>("CiJobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CiRunId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CiRunUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CiJobName", "CiBuildNumber")
                        .IsUnique();

                    b.HasIndex("RepositoryId", "StartedAtUtc");

                    b.ToTable("Build", (string)null);
                });

            modelBuilder.Entity("Jenkins.Domain.Builds.BuildArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("ProducedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BuildId");

                    b.ToTable("BuildArtifact", (string)null);
                });

            modelBuilder.Entity("Jenkins.Domain.Handoffs.ContainerReleaseHandoff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArtifactUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("BuildArtifactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeployableComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeployableUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeploymentReleaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestedByPrincipal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SemanticVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("SettledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildArtifactId");

                    b.HasIndex("DeploymentReleaseId");

                    b.HasIndex("BuildId", "Status");

                    b.ToTable("ContainerReleaseHandoff", (string)null);
                });

            modelBuilder.Entity("Jenkins.Domain.PipelineRuns.PipelineRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PipelineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("_steps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Steps");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId");

                    b.HasIndex("StartedAtUtc");

                    b.ToTable("PipelineRun", (string)null);
                });

            modelBuilder.Entity("Jenkins.Domain.Pipelines.Pipeline", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Pipeline", (string)null);
                });

            modelBuilder.Entity("Jenkins.Domain.Pipelines.PipelineStage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpstreamJobName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("_parameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Parameters");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId", "Order");

                    b.ToTable("PipelineStage", (string)null);
                });

            modelBuilder.Entity("Jenkins.Domain.SourceRepositories.DeployableComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoPublish")
                        .HasColumnType("bit");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("DeployableUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeployableUnitName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "ContainerName")
                        .IsUnique();

                    b.ToTable("DeployableComponent", (string)null);
                });

            modelBuilder.Entity("Jenkins.Domain.SourceRepositories.SourceRepository", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowContainerPublish")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("AppHostPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BaseVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("BuildKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("CiJobName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GitUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SourceRepository", (string)null);
                });

            modelBuilder.Entity("Jenkins.Domain.Builds.ArtifactPublication", b =>
                {
                    b.HasOne("Jenkins.Domain.Builds.BuildArtifact", null)
                        .WithMany("Publications")
                        .HasForeignKey("BuildArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jenkins.Domain.Builds.Build", b =>
                {
                    b.OwnsOne("Jenkins.Domain.Builds.BuildQuality", "Quality", b1 =>
                        {
                            b1.Property<Guid>("BuildId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("SbomUri")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("SbomUri");

                            b1.Property<string>("VulnerabilityReportUri")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("VulnerabilityReportUri");

                            b1.HasKey("BuildId");

                            b1.ToTable("Build");

                            b1.WithOwner()
                                .HasForeignKey("BuildId");
                        });

                    b.OwnsOne("Jenkins.Domain.Builds.BuildVersions", "Versions", b1 =>
                        {
                            b1.Property<Guid>("BuildId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AssemblyVersion")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AssemblyVersion");

                            b1.Property<string>("BaseVersion")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("BaseVersion");

                            b1.Property<string>("FileVersion")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("FileVersion");

                            b1.Property<string>("InformationalVersion")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("InformationalVersion");

                            b1.Property<string>("PackageVersion")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("PackageVersion");

                            b1.HasKey("BuildId");

                            b1.ToTable("Build");

                            b1.WithOwner()
                                .HasForeignKey("BuildId");
                        });

                    b.OwnsOne("Jenkins.Domain.Builds.SourceRevision", "SourceRevision", b1 =>
                        {
                            b1.Property<Guid>("BuildId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Author")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("CommitAuthor");

                            b1.Property<string>("Branch")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Branch");

                            b1.Property<string>("CommitSha")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("CommitSha");

                            b1.Property<string>("CommitShort")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("nvarchar(40)")
                                .HasColumnName("CommitShort");

                            b1.Property<DateTimeOffset?>("CommittedAtUtc")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("CommittedAtUtc");

                            b1.Property<string>("Message")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)")
                                .HasColumnName("CommitMessage");

                            b1.HasKey("BuildId");

                            b1.ToTable("Build");

                            b1.WithOwner()
                                .HasForeignKey("BuildId");
                        });

                    b.Navigation("Quality");

                    b.Navigation("SourceRevision")
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Jenkins.Domain.Builds.BuildArtifact", b =>
                {
                    b.HasOne("Jenkins.Domain.Builds.Build", null)
                        .WithMany("Artifacts")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jenkins.Domain.Pipelines.PipelineStage", b =>
                {
                    b.HasOne("Jenkins.Domain.Pipelines.Pipeline", null)
                        .WithMany("_stages")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jenkins.Domain.SourceRepositories.DeployableComponent", b =>
                {
                    b.HasOne("Jenkins.Domain.SourceRepositories.SourceRepository", null)
                        .WithMany("Components")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jenkins.Domain.Builds.Build", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("Jenkins.Domain.Builds.BuildArtifact", b =>
                {
                    b.Navigation("Publications");
                });

            modelBuilder.Entity("Jenkins.Domain.Pipelines.Pipeline", b =>
                {
                    b.Navigation("_stages");
                });

            modelBuilder.Entity("Jenkins.Domain.SourceRepositories.SourceRepository", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
